name: recipe
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.12
  webview_flutter: ^4.2.3
  share_plus: ^7.1.0
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_html: ^3.0.0-beta.2
  provider: ^6.0.5
 # webview_flutter: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Pacifico
      fonts:
        - asset: lib/assets/fonts/Pacifico-Regular.ttf

  # Add your other configurations below
